src/models.py
from src import db_engine


class PokemonSchema(db_engine.Document):
    key = db_engine.IntField()
    name = db_engine.StringField()
    base_experience = db_engine.IntField()
    height = db_engine.IntField()
    weight = db_engine.IntField()
    types = db_engine.ListField(db_engine.StringField(), default=list)
    image_url = db_engine.URLField()


class TradeSchema(db_engine.Document):
    pokemons_p1 = db_engine.ListField(db_engine.IntField(), default=list)
    pokemons_p2 = db_engine.ListField(db_engine.IntField(), default=list)

src/__init__.py
# Examples of valid version strings
# 'X.Y.Z.devW'
# X: major modifications
# Y: minor modifications
# Z: bug fixes
# W: developmental release (build number)

__version__ = '1.2.0'


import os

from flask import Flask
from flask_cors import CORS
from flask_mongoengine import MongoEngine

db_engine = MongoEngine()


def create_app(mode='app'):
    """Create Flask app.

    This function starts Flask, with its routers, and MongoDB host settings.

    Returns:
        app (:obj:`Flask`) Flask object reference.
    """
    app = Flask(__name__)
    if mode == 'app':
        mongodb_pwd = os.environ.get('MONGODB_PWD')
        mongodb = f'mongodb+srv://bxblue:{mongodb_pwd}@cluster0.fk2ly' \
                '.mongodb.net/poketrader?retryWrites=true&w=majority'
    else:
        mongodb = 'mongodb://localhost:27017'

    app.config['MONGODB_SETTINGS'] = {
        'host': mongodb
    }

    db_engine.init_app(app)

    from src.routers.general import general_api as general_api_blueprint
    app.register_blueprint(general_api_blueprint)

    from src.routers.pokemon import pokemon_api as pokemon_api_blueprint
    app.register_blueprint(pokemon_api_blueprint)

    from src.routers.history import history_api as history_api_blueprint
    app.register_blueprint(history_api_blueprint)

    CORS(app)

    return app

src/main.py
import os

import click

from src import create_app
from src.collector import pokemon


def check_envs():
    """Checks environment variables.

    The MONGODB_PWD is a needed variable to enable mongodb connection.

    Returns:
        bool: If all needed environment variables are set.
    """
    if not os.environ.get('MONGODB_PWD', False):
        return False
    return True


def start():
    """Start APP.

    Flask server details: host 0.0.0.0 and default port 8000.
    The HEROKU variable is used to allow the app to switch between
    production and develop environment.
    """
    print('Poke trader started.')

    if not check_envs():
        print('There are important environment variables that are not set, e.g.'
              ' MONGODB_PWD.')
        quit()

    port = int(os.environ.get('PORT', 8000))
    prod = True if os.environ.get('HEROKU') == 'TRUE' else False
    app = create_app()
    app.run(
        host='0.0.0.0',
        port=port,
        debug=not prod,
        use_reloader=not prod,
    )


@click.group(invoke_without_command=True)
@click.option('--start', is_flag=True, required=False,
              help='Start DB data.')
@click.option('--delete', is_flag=True, required=False,
              help='Delete DB data.')
def db_start(start, delete):
    """Start Poke Trader DB manager.

    Starts Poke Trader database manager.

    Args:
        start (bool): Flag to starts database creation.
        delete (bool): Flag to starts database removal.
    """
    print('Poke trader DB manager started.')
    if start:
        # collect all pokemon names and details
        pokemon.builder()
    elif delete:
        print('Delete not implemented yet.')

src/routers/general/__init__.py
from flask import Blueprint

general_api = Blueprint('general_api', __name__)

from . import views

src/routers/general/views.py
from flask import render_template

from . import general_api


@general_api.route('/', methods=['GET'])
def home():
    return render_template('index.html')

src/routers/history/__init__.py
from flask import Blueprint

history_api = Blueprint('history_api', __name__)

from . import views

src/routers/history/views.py
from flask import jsonify, render_template

from src.models import TradeSchema
from src.service import hist_builder

from . import history_api


@history_api.route('/history', methods=['GET'])
def get_history_menu():
    pokemons_lists = TradeSchema.objects()
    players_lists = hist_builder.build_players_lists(pokemons_lists)
    return render_template('history.html', detail=players_lists)

src/routers/pokemon/__init__.py
from flask import Blueprint

pokemon_api = Blueprint('pokemon_api', __name__)

from . import views

src/routers/pokemon/views.py
from flask import jsonify, render_template, request

from src.models import PokemonSchema
from src.service import calculator

from . import pokemon_api


@pokemon_api.route('/list/pokemon', methods=['GET'])
def get_pokemon_menu():
    pokemons = PokemonSchema.objects()[:200]
    return render_template('pokemon.html', pokemon_list=pokemons)


@pokemon_api.route('/pokemon/<poke_id>', methods=['GET'])
def get_pokemon(poke_id):
    pokemon = PokemonSchema.objects(key=poke_id).first()
    return jsonify({'results': render_template('pokedex.html',
                   detail=pokemon)})


@pokemon_api.route('/trade', methods=['POST'])
def trade_pokemon():
    body = request.json['data']
    p1, p2 = body[0], body[1]
    base_exps = calculator.manager_calc_base_exp(p1, p2)
    result = calculator.save_trade(p1, p2, base_exps)
    if result['status'] == 200:
        msg = {'msg': 'Successful trade!', **result}
    else:
        msg = {'msg': f'Trade is not fair. You need to add more '
                      f'{result["diff_points"]} points to player '
                      f'{result["smallest_score"]}', **result}
    return jsonify(msg), 200

src/templates/history.html
{% extends 'index.html' %}

{% block content %}

    <div class="row">
        <div class="col s6">
            <div class="card-panel">
                <div class="card-content red-text">
                    <span class="card-title">Player 1</span>
                </div>
            </div>
        </div>
        <div class="col s6">
            <div class="card-panel">
                <div class="card-content red-text">
                    <span class="card-title">Player 2</span>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        {% for players_lists in detail %}
            <div class="col s6">
                <div class="card-panel pokemon-history-card">
                    {% for pokemon in players_lists.player_1 %}
                        <img class="responsive-img circle"
                            src="{{ pokemon.image_url }}">
                    {% endfor %}
                </div>
            </div>

            <div class="col s6">
                <div class="card-panel pokemon-history-card">
                    {% for pokemon in players_lists.player_2 %}
                        <img class="responsive-img circle"
                            src="{{ pokemon.image_url }}">
                    {% endfor %}
                </div>
            </div>
        {% endfor %}

{% endblock %}

src/templates/index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Poke Trader</title>
    <link rel="icon" type="image/png"
          href="{{ url_for('static', filename='image/poke.png') }}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    
    <link rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <link rel="stylesheet"
          href="{{ url_for('static', filename='css/styles.css') }}">
  </head>
  <body>

    <nav class="navbar">
      <div class="nav-wrapper">
        <a href="{{ url_for('general_api.home') }}" class="brand-logo center">
          Poke Trader
        </a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <a href="{{ url_for('pokemon_api.get_pokemon_menu') }}">
              <i class="material-icons left large">cached</i>
              Trade
            </a>
          </li>
          <li>
            <a href="{{ url_for('history_api.get_history_menu') }}">
              <i class="material-icons left large">history</i>
              History
            </a>
          </li>
        </ul>
      </div>
    </nav>

    {% block content %}
      <div class="parallax-container">
        <div class="parallax">
          <img src="{{ url_for('static', filename='image/pokemon_wall.jpg') }}"></div>
      </div>
      <div class="container">
        <div class="section">
            <h2 class="header">Trade Steps</h2>
            <p class="grey-text text-darken-3 lighten-3">
              <div class="row center">
                <div class="col s12">
                  <img src="{{ url_for('static', filename='image/poke_trader.png') }}">
                </div>
              </div>
            </p>
        </div>
      </div>
      <div class="parallax-container">
        <div class="parallax"><img src="https://swordshield.pokemon.com/assets/img/articles/camp_art_2x.jpg"></div>
      </div>
    {% endblock %}

    <script type="text/javascript"
            src="{{ url_for('static', filename='js/jquery.min.js') }}">
    </script>

    <script type="text/javascript"
            src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js">
    </script>
  
    <script type="text/javascript"
            src="{{ url_for('static', filename='js/local.js') }}"></script>
  </body>
</html>

src/templates/pokedex.html
<div class="card-panel pokemon-detail-card">
    <div class="row">
        <div class="col s12 center-align">
            <img id="pokemon-image" class="responsive-img" src="{{ detail.image_url }}">
        </div>
    </div>
    <div class="row">
        <div class="col s12 m6 left-align">
            <span class="label"><strong>Name:</strong></span><br>
            <span class="label"><strong>Height:</strong></span><br>
            <span class="label"><strong>Weight:</strong></span><br>
            <span class="label"><strong>Experience:</strong></span>
        </div>
        <div class="col s12 m6 right-align">
            <span class="value">{{ detail.name }}</span><br>
            <span class="value">{{ detail.height }}</span><br>
            <span class="value">{{ detail.weight }}</span><br>
            <span class="value">{{ detail.base_experience }}</span>
        </div>
    </div>
    <div class="row">
        <div class="col s12 center-align">
            <a id="{{ detail.key }}" class="pokemon-add waves-effect waves-light btn">ADD</a>
        </div>
    </div>
    <a class="hide waves-effect waves-light btn modal-trigger" href="#modal1"></a>
    <div id="modal1" class="modal">
        <div class="modal-content">
            <h4>Pokemon Trade Result</h4>
            <p></p>
        </div>
        <div class="modal-footer">
            <a href="#!" class="modal-close waves-effect waves-green btn-flat">OK</a>
        </div>
    </div>
</div>

<script type="text/javascript"
        src="{{ url_for('static', filename='js/pokemon.js') }}"></script>

src/templates/pokemon.html
{% extends 'trade.html' %}

<div class="row">
    {% block pokedex %} 
        <div id="pokemon-detail"></div>    
    {% endblock %}

    {% block pokemon_list %}

        <div class="card-panel pokemon-card">
            {% for pokemon in pokemon_list %}
                <a id="pokemon" href="{{ url_for('pokemon_api.get_pokemon', poke_id=pokemon.key) }}">
                    <img class="responsive-img circle"
                        src="{{ pokemon.image_url }}">
                </a>
            {% endfor %}
        </div>

    {% endblock %}

    {% block trade_window %}
        <div class="card-panel players-card">
            <ul id="tabs-players" class="tabs">
                <li class="tab col s6"><a class="active" id="player" href="#player-1">Player 1</a></li>
                <li class="tab col s6"><a id="player" href="#player-2">Player 2</a></li>
            </ul>
            <div class='player-card'>
                <div id="player-1" class="col s12">
                    <div id="player-1-detail"></div>
                </div>
                <div id="player-2" class="col s12">
                    <div id="player-2-detail"></div>
                </div>
            </div>
            <div class="row">
                <div class="col s12 m6 center-align">
                    <a id="trade-pokemon" class="waves-effect waves-light btn">Trade</a>
                </div>
                <div class="col s12 m6 center-align">
                    <a class="remove-all waves-effect waves-light btn red ">Clear</a>
                </div>
            </div>
        </div>
    {% endblock %}
</div>

src/templates/trade.html
{% extends 'index.html' %}

{% block content %}

    <div class="container">
        <div class="row">
            <div class="col s12 m4 l3">
                {% block pokedex %}
                {% endblock %}
            </div>
            
            <div class="col s12 m4 l5">
                {% block pokemon_list %}
                {% endblock %}
            </div>
            
            <div class="col s12 m4 l4">
                {% block trade_window %}
                {% endblock %}
            </div>
        </div>
    </div>

{% endblock %}